// ── Iconos compartidos del proyecto ──
// Todos los iconos usan lucide-react con size=18 y strokeWidth=2 por defecto.
// Importar desde aquí en lugar de usar SVGs inline.

export {
  LayoutDashboard,
  ShoppingCart,
  TrendingDown,
  ArrowUpRight,
  ArrowDownLeft,
  Wallet,
  FileText,
  Users,
  DollarSign,
  Package,
  Warehouse,
  ShoppingBag,
  Boxes,
  UserCircle,
  Building2,
  User,
  UsersRound,
  CreditCard,
  HelpCircle,
  QrCode,
  Calendar,
  Printer,
  Sparkles,
  Lock,
  Plus,
  Edit,
  Archive,
  RotateCcw,
  Eye,
  Copy,
  Search,
  X,
  ChevronDown,
  Menu,
  LogOut,
  AlertTriangle,
  Info,
  Check,
  Clock,
  Tag,
  Ban,
  FileCheck,
  Layers,
  Link,
  Mail,
  Phone,
  PrinterIcon,
  Trash2,
  MoreHorizontal,
  GripVertical,
  type LucideIcon,
} from 'lucide-react'

// Helper para iconos con tamaño consistente
export function iconSize(size = 18) {
  return { size, strokeWidth: 2 } as const
}
