-- ================================================================
-- MIGRACIÓN 014: Módulo de Ventas (Fase 1)
--
-- Implementa el flujo Oferta Comercial → Factura.
--
-- Documentos:
--   ofertas   → cotización editable, estados:
--               BORRADOR | ENVIADA | APROBADA | RECHAZADA | CADUCADA
--   facturas  → documento fiscal, estados:
--               BORRADOR | EMITIDA | COBRADA | ANULADA
--
-- Una oferta APROBADA genera automáticamente una factura en BORRADOR
-- copiando líneas y ajustes (campo ofertas.factura_id queda con la FK).
--
-- Líneas y ajustes se comparten entre ambos documentos vía tablas
-- unificadas (documento_lineas, documento_ajustes) usando documento_tipo.
--
-- Numeración: por empresa, anual, con letra distintiva.
--   Oferta:  OF{LETRA}{AAAA}{####}   ej: OFM20260001
--   Factura: F{LETRA}{AAAA}{####}    ej: FM20260001
-- ================================================================

-- ── Consecutivos ──────────────────────────────────────────────────────────────

create table if not exists consecutivos_venta (
  client_id      text not null,
  empresa_id     text not null,
  tipo           text not null,             -- 'OFERTA' | 'FACTURA'
  anio           int  not null,
  ultimo_numero  int  not null default 0,
  updated_at     timestamptz not null default now(),
  primary key (client_id, empresa_id, tipo, anio)
);

-- ── Ofertas ───────────────────────────────────────────────────────────────────

create table if not exists ofertas (
  oferta_id        text          primary key,         -- OFE-XXXXXXXX (interno)
  numero           text          not null,            -- OF{LETRA}{AAAA}{####}
  client_id        text          not null,
  empresa_id       text          not null,
  cliente_id       text          not null,
  fecha_emision    date          not null default current_date,
  fecha_validez    date,
  moneda           text          not null,
  estado           text          not null default 'BORRADOR',
                   -- BORRADOR | ENVIADA | APROBADA | RECHAZADA | CADUCADA
  subtotal         numeric(18,2) not null default 0,
  total            numeric(18,2) not null default 0,
  notas            text,
  factura_id       text,                              -- FK si fue convertida
  created_at       timestamptz   not null default now(),
  updated_at       timestamptz   not null default now()
);

create unique index if not exists ofertas_numero_unique
  on ofertas (client_id, numero);

create index if not exists idx_ofertas_emp_estado
  on ofertas (client_id, empresa_id, estado);

create index if not exists idx_ofertas_cliente
  on ofertas (client_id, cliente_id);

-- ── Facturas ──────────────────────────────────────────────────────────────────

create table if not exists facturas (
  factura_id          text          primary key,      -- FAC-XXXXXXXX (interno)
  numero              text          not null,         -- F{LETRA}{AAAA}{####}
  client_id           text          not null,
  empresa_id          text          not null,
  oferta_id           text,                           -- nullable: si vino de oferta
  cliente_id          text          not null,
  fecha_emision       date          not null default current_date,
  fecha_vencimiento   date,
  moneda              text          not null,
  estado              text          not null default 'BORRADOR',
                      -- BORRADOR | EMITIDA | COBRADA | ANULADA
  subtotal            numeric(18,2) not null default 0,
  total               numeric(18,2) not null default 0,
  notas               text,
  created_at          timestamptz   not null default now(),
  updated_at          timestamptz   not null default now()
);

create unique index if not exists facturas_numero_unique
  on facturas (client_id, numero);

create index if not exists idx_facturas_emp_estado
  on facturas (client_id, empresa_id, estado);

create index if not exists idx_facturas_cliente
  on facturas (client_id, cliente_id);

-- ── Líneas (unificadas) ───────────────────────────────────────────────────────

create table if not exists documento_lineas (
  linea_id         bigint generated by default as identity primary key,
  documento_tipo   text          not null,   -- 'OFERTA' | 'FACTURA'
  documento_id     text          not null,
  orden            int           not null default 0,
  producto_id      text,                     -- nullable: permite texto libre
  descripcion      text          not null,
  cantidad         numeric(18,3) not null,
  precio_unitario  numeric(18,2) not null,
  total            numeric(18,2) not null
);

create index if not exists idx_lineas_doc
  on documento_lineas (documento_tipo, documento_id, orden);

-- ── Ajustes (descuentos, cargos, impuestos) ───────────────────────────────────

create table if not exists documento_ajustes (
  ajuste_id        bigint generated by default as identity primary key,
  documento_tipo   text          not null,   -- 'OFERTA' | 'FACTURA'
  documento_id     text          not null,
  orden            int           not null default 0,
  tipo             text          not null,   -- 'DESCUENTO' | 'CARGO' | 'IMPUESTO'
  nombre           text          not null,   -- libre: 'ISV 10%', 'Flete'…
  modo             text          not null,   -- 'PORCENTAJE' | 'MONTO_FIJO'
  valor            numeric(18,4) not null,
  monto_calculado  numeric(18,2) not null
);

create index if not exists idx_ajustes_doc
  on documento_ajustes (documento_tipo, documento_id, orden);

-- ── RLS y grants ──────────────────────────────────────────────────────────────

alter table public.consecutivos_venta  enable row level security;
alter table public.ofertas             enable row level security;
alter table public.facturas            enable row level security;
alter table public.documento_lineas    enable row level security;
alter table public.documento_ajustes   enable row level security;

grant select, insert, update, delete on public.consecutivos_venta  to service_role;
grant select, insert, update, delete on public.ofertas             to service_role;
grant select, insert, update, delete on public.facturas            to service_role;
grant select, insert, update, delete on public.documento_lineas    to service_role;
grant select, insert, update, delete on public.documento_ajustes   to service_role;

-- Secuencias para columnas IDENTITY (documento_lineas, documento_ajustes)
grant usage, select on all sequences in schema public to service_role;

notify pgrst, 'reload schema';
