-- ================================================================
-- MIGRACIÓN 036: Inventario · Compras integradas con la base — Fase 5
--
-- Documento de compra a proveedor (cabecera + líneas), espejo de las
-- ventas. Numeración correlativa por empresa y año: COM-AAAA-####.
--
-- Estados: BORRADOR | CONFIRMADA | ANULADA.
--   Al CONFIRMAR (igual que la nómina crea el gasto 'Salarios'):
--     1. genera movimientos ENTRADA de stock por cada línea hacia almacen_id
--     2. crea un GASTO 'Compras' en gastos_cobros (monto = total) que fluye a
--        CxP / Tesorería / Reportes por la liquidación unificada; guarda gasto_id.
--   Al ANULAR: revierte el stock y borra el gasto si no tiene liquidaciones.
--
-- Numeración interna: CMP-XXXXXXXX.
-- ================================================================

-- Consecutivo de compras por (cliente, empresa, año)
create table if not exists consecutivos_compra (
  client_id      text not null,
  empresa_id     text not null,
  anio           int  not null,
  ultimo_numero  int  not null default 0,
  updated_at     timestamptz not null default now(),
  primary key (client_id, empresa_id, anio)
);

-- Cabecera de compra
create table if not exists compras (
  compra_id    text          primary key,                  -- CMP-XXXXXXXX (interno)
  numero       text          not null,                     -- COM-AAAA-####
  client_id    text          not null,
  empresa_id   text          not null,
  proveedor_id text,                                       -- third_parties (nullable: texto libre)
  almacen_id   text          not null,                     -- destino de la entrada de stock
  fecha        date          not null default current_date,
  moneda       text          not null,
  estado       text          not null default 'BORRADOR',  -- BORRADOR | CONFIRMADA | ANULADA
  total        numeric(18,2) not null default 0,
  notas        text,
  gasto_id     text,                                       -- FK → gastos_cobros al confirmar
  created_at   timestamptz   not null default now(),
  updated_at   timestamptz   not null default now()
);

create unique index if not exists compras_numero_unique on compras (client_id, numero);
create index if not exists idx_compras_emp_estado on compras (client_id, empresa_id, estado);
create index if not exists idx_compras_proveedor  on compras (client_id, proveedor_id);

-- Líneas de compra
create table if not exists compra_lineas (
  linea_id        bigint generated by default as identity primary key,
  compra_id       text          not null,
  client_id       text          not null,
  orden           int           not null default 0,
  producto_id     text,                                    -- nullable: permite texto libre
  descripcion     text          not null,
  cantidad        numeric(18,3) not null,
  costo_unitario  numeric(18,2) not null,
  total           numeric(18,2) not null
);

create index if not exists idx_compra_lineas_doc on compra_lineas (compra_id, orden);

-- RLS y grants
alter table public.consecutivos_compra enable row level security;
alter table public.compras             enable row level security;
alter table public.compra_lineas       enable row level security;

grant select, insert, update, delete on public.consecutivos_compra to service_role;
grant select, insert, update, delete on public.compras             to service_role;
grant select, insert, update, delete on public.compra_lineas       to service_role;

-- Secuencia IDENTITY de compra_lineas
grant usage, select on all sequences in schema public to service_role;

notify pgrst, 'reload schema';
