-- ================================================================
-- 097 · Versionado de `audit_log` (registro de actividad del admin)
-- La tabla ya existe en prod (la escribe src/lib/audit.ts, la lee
-- /admin/actividad) pero nunca tuvo DDL versionado — brecha de
-- reproducibilidad de entorno. Este CREATE ... IF NOT EXISTS replica el
-- esquema real sin tocar los datos existentes. Sin RLS: coherente con el
-- resto de tablas (multi-tenant por app, no por RLS).
-- ================================================================

create table if not exists audit_log (
  id          bigint generated by default as identity primary key,
  created_at  timestamptz default now(),
  user_email  text not null,
  entity      text not null,   -- cliente|plan|pago|sistema|modulo_catalogo|modulo_cliente|diagnostico_necesidad|usuario|presupuesto
  entity_id   text,
  action      text not null,
  description text not null
);

create index if not exists audit_log_created_idx on audit_log (created_at desc);
create index if not exists audit_log_entity_idx  on audit_log (entity, entity_id);
