-- ================================================================
-- MIGRACIÓN 198: Firma de documentos legales del cliente
--
-- Durante el período de prueba (cláusula 3 del contrato) el cliente firma y
-- acepta, desde su perfil del portal, tres documentos: el NDA, el contrato de
-- servicio y el presupuesto (Anexo I con sus módulos y tarifas). La firma es
-- electrónica SIMPLE (válida bajo eIDAS / Ley 6/2020): casilla de aceptación +
-- nombre escrito, con registro de fecha/hora, IP, user-agent, versión de la
-- plantilla firmada y un hash SHA-256 del contenido exacto que se le mostró.
-- El hash es lo que hace la firma verificable: pinta qué texto se aceptó, no un
-- "aceptó algo".
--
-- El texto legal (NDA/contrato) vive versionado EN CÓDIGO (src/lib/documentos/),
-- no aquí: así el mismo render alimenta la pantalla y el PDF y el hash cuadra.
-- Esta tabla solo guarda el ACTO de firma y el PDF resultante.
--
-- Multi-tenant como todo el repo: `client_id` en cada fila, sin RLS por tenant
-- (la app filtra por client_id). Patrón RLS de mig. 083/092.
-- ================================================================

create table if not exists firmas_documentos (
  id                  bigint generated by default as identity primary key,
  client_id           text        not null references clients(client_id) on delete cascade,
  -- Los tres documentos del alta. Un `check` y no una FK: el catálogo de tipos
  -- es fijo y vive en código, no es dato que el cliente edite.
  tipo                text        not null check (tipo in ('nda', 'contrato', 'presupuesto')),
  version             text        not null,          -- versión de la plantilla firmada (p. ej. 'nda-2026-08')
  doc_hash            text        not null,          -- sha256 del contenido exacto renderizado
  firmado_por_user    text,                          -- user_id de client_users (quién firmó)
  firmado_por_nombre  text        not null,          -- nombre escrito al firmar
  firmado_por_email   text        not null,
  firmado_at          timestamptz not null default now(),
  ip                  text,
  user_agent          text,
  -- Datos exactos que se mostraron al firmar (Anexo I resuelto, datos de empresa
  -- y de proveedor). Congela lo aceptado aunque los módulos o las tarifas cambien
  -- después: la firma vale por lo que decía ese día, no por lo que diga hoy.
  snapshot            jsonb       not null default '{}'::jsonb,
  pdf_path            text,                          -- ruta en el bucket privado documentos-firmados (null si falló la subida)
  created_at          timestamptz not null default now(),
  -- Una firma por documento-versión y cliente: reintentar firmar el mismo
  -- documento no duplica (la acción trata la violación 23505 como "ya firmado").
  unique (client_id, tipo, version)
);

create index if not exists idx_firmas_client on firmas_documentos (client_id);

alter table public.firmas_documentos enable row level security;
grant select, insert, update, delete on public.firmas_documentos to service_role;
drop policy if exists "admin_full_access" on public.firmas_documentos;
create policy "admin_full_access" on public.firmas_documentos
  for all to authenticated using (true) with check (true);

-- Bucket PRIVADO para los PDF firmados. A diferencia de `contratos` (mig. 099,
-- público y servido con getPublicUrl), un NDA/contrato firmado es confidencial:
-- se sirve SIEMPRE con createSignedUrl (URL temporal), nunca getPublicUrl.
insert into storage.buckets (id, name, public)
values ('documentos-firmados', 'documentos-firmados', false)
on conflict (id) do nothing;

notify pgrst, 'reload schema';
